### PR TITLE
wip: Preview/oidc simplified

### PR DESCRIPTION
**Pull request by whereismyjetpack**
@ajkiessl  this PR is just for review. We'll have to modify the server configuration before deploying this code, so let me know how best to handle that and i'll work with you. in the meantime, if we can have this branch deployed to dev that would help out a bunch

### CODE REVIEW

**Comment by ajkiessl** [comment]
@whereismyjetpack I deployed this to stage.  Let me know if it needs to be on dev.  If we can get this out sometime this week or next week that would be great.  Would probably be best to release during a maintenance window (like 6-7am) if there is going to be downtime between deploying server config and the application.

**Review by ajkiessl — APPROVED** [review]

**Comment by whereismyjetpack** [comment]
Thanks! I'll update the Apache configuration tomorrow, if our testing is successful i'll work on scheduling a time for production.

**Comment by whereismyjetpack** [comment]
@ajkiessl I fully expect some of these tests to fail since i had to make some changes to the webaccess code. I found that we weren't actually authenticating users, so i added that to the controllers before_action. i think related to the ticket you put in today, a lot of the logic we have in there can proabably be removed. we could probably refactor the webaccess strategy into a more generic 'http_header' one, kind of like what RMD uses. let me know what you think!

**Comment by ajkiessl** [comment]
@whereismyjetpack I agree.  I'm going to pull down your code and take a look at it myself.  I'm going to see what deleting a bunch of the old code does.  Then get back to you in the afternoon.

**Pull request merged**
