### PR TITLE
removed excess controller authentication logic.  Moved some logic int…

### PR DESCRIPTION
**Pull request by ajkiessl**
…o the authentication strategy.

### CODE REVIEW

**Comment by ajkiessl** [comment]
@whereismyjetpack This seems to be working nicely locally, but I'm not having much luck with it deployed to stage.

**Comment by whereismyjetpack** [comment]
I'm take a look at this sometime this weekend and see if I can reproduce!

**Comment by ajkiessl** [comment]
@whereismyjetpack  I ran into several issues with the application layer authentication:

1.) If I logged in as an 'approver' of an 'admin' first, then redirected to an author path, I would be logged in as the Author record matching the database ID of the Approver/Admin I was previously logged in as.  So it had me logged in as someone else.

2.) For some reason (which has always been an issue) the authentication process runs multiple times for approver and admin paths.  This causes issues with the CSRF protection because the initial login occurs, then the auth_token to be sent to the client is generated, then the login happens again (changing the auth_token), and for some reason the first auth_token is sent to the client.  So if the client wants to send a POST, DELETE, or PATCH, it is rejected. 

I worked around these issues by:

1.) Adding logic in each of the user model controllers that signs the user out if session[:user_role] does not match the controller's user role.  If the user is signed out, then regular authentication will happen and the proper model ID will be used to set the current user.

2.)Adding a line of code in the authenticatable.rb strategy that calls 'pass' if the session[:user_name] is already set.  session[:user_name] is set in the controller if a current_user exists, so this logic will just pass over the authentication strategy if someone is already logged in.

My overall thoughts on this apps authentication is that Devise does not handle multiple user models very well.  Ideally we should just have one user model that can be flagged as an admin and can act as an approver as well.  For now, what we have works but I will consider a revamp for the future.

**Comment by whereismyjetpack** [comment]
@ajkiessl I agree, I think a refactor of users into a single model is the right answer, but probably not an easy task. Thanks for your eyes, and work on this. This all looks good!

**Pull request merged**
